name: 1. Missing Items/IDs 🙈
description: Send in some Items/IDs to add to existing categories
title: "Missing IDs"
labels: ["missing ids"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report these IDs!
  - type: input
    id: category
    attributes:
      label: Category Name
      description: In which category do the following items/IDs belong?
      placeholder: Steamy Romance Novels
    validations:
      required: true
  - type: textarea
    id: urls
    attributes:
      label: URLs
      description: Fill this with Wowhead or WoWDB urls with the missing items. Collection pages are fine, if complete. Fill either this OR the IDs field below. **One per line.**
      placeholder: |
        https://www.wowhead.com/item=137199/a-steamy-romance-novel
        https://www.wowhead.com/item=137200/a-steamy-romance-novel-forbidden-love
        https://www.wowhead.com/item=137201/a-steamy-romance-novel-northern-exposure
        ...
  - type: textarea
    id: ids
    attributes:
      label: Item IDs
      description: Enter IDs here. Only IDs and *nothing* else is required here. Fill either this OR the Wowhead above. **One per line.**
      render: Shell
      placeholder: |
        137199
        137200
        137201
        ...