name: 3. Items/IDs in the wrong category 🧀
description: Send in some Items/IDs which are in the wrong category
title: "Items in wrong category"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report these IDs!
  - type: input
    id: category
    attributes:
      label: Category Name
      description: In which category do the following items/IDs *actually* belong?
      placeholder: Steamy Romance Novels
    validations:
      required: true
  - type: textarea
    id: ids
    attributes:
      label: Item IDs / Item Names
      description: Enter IDs or Item Names here. **One per line.**
      render: Shell
      placeholder: |
        137199
        137200
        137201
        ...