blank_issues_enabled: false
contact_links:
  - name: Addon on CurseForge
    url: https://www.curseforge.com/wow/addons/adibags-shadowlands
    about: Alternatively feel free to leave a  comment on the CurseForge Page - sometimes it even sends me an email...
  - name: Send me a personal message on CurseForge
    url: https://www.curseforge.com/private-messages/send?recipient=zottelchen
    about: Another way to get in contact with me.