# This is a basic workflow to help you get started with Actions

name: Lua Check✔️

# Controls when the action will run.
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # we first have to clone the AddOn project, this is a required step
      - name: Clone project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # gets entire git history, needed for automatic changelogs
          path: ./variant

      - name: Get Zottelchen/adibags-creator-action
        uses: actions/checkout@v3
        with:
            repository: Zottelchen/adibags-creator-action
            ref: refs/heads/main
            persist-credentials: false
            path: ./action
      - name: Merge
        run: |
          cp -r ./variant/* ./action
          mkdir ./dist
          cp ./variant/.pkgmeta ./dist/.pkgmeta
          mv ./action/* .
          cp -r ./variant/.git .
          rm -rf ./action ./variant
          ls -la .
      - name: Build AdiBags Extension
        uses: ./
        env:
          PYTHONUNBUFFERED: 1
          DEBUG: 1
          BLIZZ_ID: ${{ secrets.BLIZZ_ID }}
          BLIZZ_SECRET: ${{ secrets.BLIZZ_SECRET }}
          ADDON_VARIANT: "DEBUG"
          ADDON_COLOR: "FFFFFF"
          TOC_VERSION: "DEBUG"
          CURSE_ID: "DEBUG"
          WOW_INTERFACE_ID: "DEBUG"
          WAGO_ID: "DEBUG"
      - name: Copy Output
        run: |
          cp -r ./out/* ./dist
          cp -r ./out/.git ./dist
          ls -la ./dist
          cd ./dist
          git add *
      - name: Luacheck linter
        uses: lunarmodules/luacheck@v0
        with:
            args: dist/AdiBags_DEBUG.lua --ignore 113 211 212 611 614 631
            # ignored (see https://luacheck.readthedocs.io/en/stable/warnings.html):
            # 113: Accessing an undefined global variable. - There are bound to be some as this an addon, as there are some functions which are known to WoW only.
            # 211: Unused local variable. - Not important.
            # 212: Unused argument. - Not important.
            # 611: A line consists of nothing but whitespace. - Oh no! Oh wait, not important.
            # 614: Trailing whitespace in a comment. - These reports are just plain wrong.
            # 631: Line is too long. - Not important.